name: 'Svelte Check'
description: 'Provides a Svelte Check readout'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
    icon: 'search'
    color: 'orange'

inputs:
    paths:
        description: 'The path(s) to run svelte-check from, one per line'
        required: false
        default: '.'
    failOnError:
        description: 'Should we cause CI to fail if there is a Svelte Check error?'
        required: false
        default: 'true'
    failOnWarning:
        description: 'Should we cause CI to fail if there is a Svelte Check warning?'
        required: false
        default: 'false'
    failFilter:
        description: 'When failFilter is set and either failOnError or failOnWarning is enabled, the action will only fail for issues that occur in paths matching these globes.'
        required: false
        default: '**'

runs:
    using: 'node20'
    main: 'dist/index.js'
